---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: namespace1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - image: gcr.io/google_containers/echoserver:1.10
        name: echoserver
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: namespace1
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: echoserver
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echoserver
  namespace: namespace1
  #annotations:
    #kubernetes.io/tls-acme: "true"
    #kubernetes.io/ingress.class: "nginx"
spec:
# tls:
# - hosts:
#   - hello.example.com
#   secretName: echoserver-tls
  rules:
  - host: hello.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echoserver
            port: 
              number: 80
