apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: shell2
  name: shell2
  namespace: namespace2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shell2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: shell2
    spec:
      containers:
      - image: centos:8
        name: centos
        command: [ '/bin/sleep', '3600' ]
        resources: {}
      nodeSelector:
        zone: B
status: {}
